name: pixel_forge
description: Offline-first image compression and resizing utility by Livinlabs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_image_compress: ^2.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  share_plus: ^12.0.1
  google_fonts: ^8.0.2
  gap: ^3.0.1
  image_size_getter: ^2.4.1
  # Ads + IAP
  google_mobile_ads: ^5.3.0
  in_app_purchase: ^3.2.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
