name: pixel_forge
description: Offline-first image compression and resizing utility by Livinlabs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_image_compress: ^2.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  share_plus: ^12.0.1
  google_fonts: ^8.0.2
  gap: ^3.0.1
  image_size_getter: ^2.4.1
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.0
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  change_app_package_name: ^1.5.0
  in_app_update: ^4.2.5
  in_app_review: ^2.0.11
  url_launcher: ^6.3.0
  package_info_plus: ^9.0.1

assets:
  - assets/icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground_inset: 12
  adaptive_icon_background: "#30CF7B"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_monochrome: "assets/icon.png"

flutter_native_splash:
  color: "#30CF7B" 
  image: "assets/icon.png"
  android_12:
    image: "assets/icon.png"
    color: "#30CF7B"
